import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

i18n.use(initReactI18next).init({
  lng: "en",
  resources: {
    en: {
      translation: {
        //Sidebar
        store: "Store",
        library: "Library",
        studios: "Studios",
        studio: "Studio",
        tradeOffers: "Trade Offers",
        adminPanel: "Admin Panel",
        getFullVersion: "Get Full Version",
        cart: "Cart",
        //Library
        yourLibrary: "Your Library",
        username: "Username",
        surname: "Surname",
        preferedTheme: "Prefered theme",
        credits: "Credits",
        noProducts: "You have currently no products.",
        //Admin
        delete: "Delete",
        addAdmin: "Add Admin",
        deleteAdmin: "Delete Admin",
        users: "Users",
        album: "Album",
        product: "Product",
        remove: "Remove",
        adminPanelUsersCount: "Active users",
        adminPanelTotalCredits: "Total credits",
        adminPanelTopContributors: "Top Contributors",
        adminPanelTopUser: "Top user",
        adminAddedSuccessfully: "Admin was added successfully.",
        adminNotAdded: "Admin could not be added.",
        adminDeletedSuccessfully: "Admin was deleted successfully.",
        adminNotDeleted: "Admin could not be deleted.",
        userDeletedSuccessfully: "User was deleted successfully.",
        userNotDeleted: "User could not be deleted.",
        ownershipChangedSuccessfully: "Ownership was changed successfully.",
        ownershipNotChanged: "Ownership could not be changed.",
        //Cart
        totalCost: "Total cost",
        noCartItems: "Your cart is empty. Add some products to proceed.",
        cartOf: "Cart of",
        addToCart: "Add to Cart",
        purchaseMadeSuccessfully: "Purchase was made successfully.",
        purchase: "Purchase",
        insufficientFunds: "Insufficient funds",
        //PurchaseHistory
        purchaseHistory: "Purchase history",
        noPurchases: "You have no purchases.",
        //Settings
        save: "Save",
        cancel: "Cancel",
        exportUserInfo: "Export user information",
        name: "Name",
        email: "Email",
        bio: "Bio",
        noBio: "You have no bio.",
        otherSettings: "Other Settings",
        themes: "Themes",
        privateData: "Private Data",
        profileSettings: "Profile Settings",
        informationAlteredSuccessfully: "Information was altered successfully",
        informationNotAltered: "Information was no altered.",
        //CreateItem
        nameOfTrack: "Name of the track",
        producer: "Producer",
        songDuration: "Song duration",
        createYourItem: "Create your item",
        createItem: "Create item",
        picPreview: "Here is a quick preview of your item picture!",
        newItemName: "How would you like your product to be called?",
        newAlbumName: "Album Name",
        newAlbumCreator: "Artist",
        newAlbumDescription: "Description",
        newAlbumPrice: "Price",
        tags: "Tags",
        provideValidProductName: "Provide a valid product name.",
        provideValidArtist: "Provide a valid artist name.",
        provideValidDescription: "Provide a valid description (at least 10 characters long).",
        provideValidPrice: "Provide a valid price.",
        selectOneTag: "Select at least 1 tag.",
        someSongTitlesInvalid: "Some of the songs' titles were invalid.",
        someSongProducersInvalid: "Some of the songs' producers were invalid.",

        //Item
        viewDetails: "View Details",
        albumDetails: "Album Details",
        otherProducts: "Other Products",
        //CreateStudio
        createYourStudio: "Create Your Studio",
        studioImagePreview: "Here is a quick preview of your studio image!",
        uploadPhoto: "Upload photo",
        studioName: "How would you like your studio to be called?",
        placeholderName: "Name",
        studioDesc: "Tell us more about your studio!",
        placeholderDesc: "Description",
        createStudioNotif: "*You will be able to make changes later on",
        createStudio: "Create Studio",
        nameLengthNotif: "*Name should contain between 3 and 30 characters",
        descLengthNotif: "*Description should contain between 10 and 100 characters",
        nameLengthError: "Provide a valid studio name (between 3 and 30 characters long).",
        descLengthError: "Provide a valid studio description (between 10 and 100 characters long).",
        nameTakenError: "Studio name is already taken.",
        //Edit studio
        editYourStudio: "Edit Your Studio",
        studioNameEdit: "What would you like your studio to be renamed to?",
        //Studio
        studioDetails: "Studio Details",
        studioOwned: "Owned by",
        otherStudios: "Other studios",
        studioAlbums: "Studio Albums",
        viewProfile: "View profile",
        //Studios
        studioDeletionMessage: "This action cannot be undone. Are you 100% sure?",
        confirm: "Confirm",
        learnMore: "Learn More",
        myStudios: "My Studios",
        edit: "Edit",
        //TopBar
        search: "Search",
        //Menu
        darkMode: "Dark Mode",
        termsOfUse: "Terms of Use",
        settings: "Settings",
        addFunds: "Add Funds",
        logout: "Logout",
        //DecideTradeOffers
        tradeFrom: "Trade from",
        youGet: "You get",
        youGive: "You give",
        accept: "Accept",
        decline: "Decline",
        user1Products: "User 1 Products",
        user2Products: "User 2 Products",
        sendTradeoffer: "Send Tradeoffer",
        //Tradeoffer
        yourInventory: "Your inventory",
        theirInventory: "Their inventory",
        itemsYouLose: "These are the items you will lose in the trade.",
        theirItems: "Their items",
        itemsYouReceive: "These are the items you will receive in the trade.",

        //Tradeoffers
        itemsYouGive: "Items you will give",

        noPendingTradeoffers: "You have no pending trade offers.",
        historyTradeoffer: "History of your trade offers",
        trader: "Trader",
        yourItems: "Your items",
        traderItems: "Trader's items",
        date: "Date",
        noPreviousTrades: "You have no previous trades.",
        tradeOfferAccept: "Accept",
        tradeOfferDecline: "Declne",
        tradeOffersUrOffer: "You offered",
        tradeOffersNoOffer: "User has no trades.",
        incommingTradeOffer: "offered you",
        offeredItem: "for your",
        accepted: "Accepted",
        declined: "Declined",
        canceled: "Canceled",
        by: "by",
        for: "for",
        sItems: "'s items",

        //User
        userDetails: "User Details",
        tradeOffer: "Trade Offer",
        checkout: "Checkout",
        userStudios: "User studios",
        Checkout: "Check out",

        //BuyKey
        appActivation: "App activation",
        verify: "Verify",
        keyPurchase: "Key purchase",
        buyLicenseKey: "Buy license key",
        clickToCopy: "Click to copy to clipboard",
      }
    },
    pl: {
      translation: {
        //Sidebar
        store: "Sklep",
        library: "Biblioteka",
        studios: "Studia",
        studio: "Studio",
        tradeOffers: "Oferty Wymiany",
        adminPanel: "Panel Admina",
        getFullVersion: "Uzyskaj pełną wersję",
        cart: "Koszyk",
        //Library
        yourLibrary: "Twoja biblioteka",
        username: "Nazwa użytkownika",
        surname: "Nazwisko",
        preferedTheme: "Preferowany motyw",
        credits: "Kredyty",
        noProducts: "Aktualnie nie masz żadnych produktów.",
        //Admin
        delete: "Usuń",
        addAdmin: "Dodaj administratora",
        deleteAdmin: "Usuń administratora",
        users: "Użytkownicy",
        album: "Album",
        product: "Produkt",
        remove: "Usuń",
        adminPanelUsersCount: "Aktywni użytkownicy",
        adminPanelTotalCredits: "Łączna liczba kredytów",
        adminPanelTopContributors: "Najwięksi współtwórcy",
        adminPanelTopUser: "Najlepszy użytkownik",
        adminAddedSuccessfully: "Administrator został pomyślnie dodany.",
        adminNotAdded: "Nie udało się dodać administratora.",
        adminDeletedSuccessfully: "Administrator został pomyślnie usunięty.",
        adminNotDeleted: "Nie udało się usunąć administratora.",
        userDeletedSuccessfully: "Użytkownik został pomyślnie usunięty.",
        userNotDeleted: "Nie udało się usunąć użytkownika.",
        ownershipChangedSuccessfully: "Własność została pomyślnie zmieniona.",
        ownershipNotChanged: "Nie udało się zmienić własności.",
        //Cart
        totalCost: "Całkowity koszt",
        noCartItems: "Twój koszyk jest pusty. Dodaj produkty, aby kontynuować.",
        cartOf: "Koszyk użytkownika",
        addToCart: "Dodaj do koszyka",
        purchaseMadeSuccessfully: "Zakup został pomyślnie dokonany.",
        purchase: "Zakup",
        insufficientFunds: "Niewystarczające środki",
        //PurchaseHistory
        purchaseHistory: "Historia zakupów",
        noPurchases: "Nie masz żadnych zakupów.",
        //Settings
        save: "Zapisz",
        cancel: "Anuluj",
        exportUserInfo: "Eksportuj informacje o użytkowniku",
        name: "Nazwa",
        email: "Email",
        bio: "Bio",
        noBio: "Nie masz opisu.",
        otherSettings: "Inne ustawienia",
        themes: "Motywy",
        privateData: "Dane prywatne",
        profileSettings: "Ustawienia profilu",
        informationAlteredSuccessfully: "Informacje zostały pomyślnie zmienione.",
        informationNotAltered: "Informacje nie zostały zmienione.",
        //CreateItem
        nameOfTrack: "Nazwa utworu",
        producer: "Producent",
        songDuration: "Czas trwania utworu w sekundach",
        createYourItem: "Utwórz swój przedmiot",
        createItem: "Utwórz przedmiot",
        picPreview: "Oto szybki podgląd zdjęcia twojego przedmiotu!",
        newItemName: "Jak chciałbyś nazwać swój produkt?",
        newAlbumName: "Nazwa albumu",
        newAlbumCreator: "Wykonawca",
        newAlbumDescription: "Opis",
        newAlbumPrice: "Cena",
        tags: "Tagi",
        provideValidProductName: "Podaj poprawną nazwę produktu.",
        provideValidArtist: "Podaj poprawną nazwę artysty.",
        provideValidDescription: "Podaj poprawny opis (co najmniej 10 znaków).",
        provideValidPrice: "Podaj poprawną cenę.",
        selectOneTag: "Wybierz co najmniej 1 tag.",
        someSongTitlesInvalid: "Niektóre tytuły piosenek są niepoprawne.",
        someSongProducersInvalid: "Niektórzy producenci piosenek są niepoprawni.",
        //Item
        viewDetails: "Zobacz szczegóły",
        albumDetails: "Szczegóły albumu",
        otherProducts: "Inne produkty",
        //CreateStudio
        createYourStudio: "Utwórz swoje studio",
        studioImagePreview: "Oto szybki podgląd obrazu Twojego studia!",
        uploadPhoto: "Prześlij zdjęcie",
        studioName: "Jak chciałbyś nazwać swoje studio?",
        placeholderName: "Nazwa",
        studioDesc: "Opowiedz nam więcej o swoim studiu!",
        placeholderDesc: "Opis",
        createStudioNotif: "*Będziesz mógł wprowadzić zmiany później",
        createStudio: "Utwórz Studio",
        nameLengthNotif: "*Nazwa powinna zawierać od 3 do 30 znaków",
        descLengthNotif: "*Opis powinien zawierać od 10 do 100 znaków",
        nameLengthError: "Podaj prawidłową nazwę studia (od 3 do 30 znaków).",
        descLengthError: "Podaj prawidłowy opis studia (od 10 do 100 znaków).",
        nameTakenError: "Nazwa studia jest już zajęta.",
        //EditStudio
        editYourStudio: "Edytuj swoje studio",
        studioNameEdit: "Jak chciałbyś nazwać swoje studio?",
        //Studio
        studioDetails: "Szczegóły studia",
        studioOwned: "Posiadane przez",
        otherStudios: "Inne studia",
        studioAlbums: "Albumy studyjne",
        viewProfile: "Zobacz profil",
        //Studios
        studioDeletionMessage: "Tej operacji nie można cofnąć. Czy jesteś pewien na 100%?",
        confirm: "Potwierdź",
        learnMore: "Dowiedz się więcej",
        myStudios: "Moje studia",
        edit: "Edytuj",
        //TopBar
        search: "Szukaj",
        //Menu
        darkMode: "Tryb ciemny",
        termsOfUse: "Regulamin",
        settings: "Ustawienia",
        addFunds: "Dodaj środki",
        logout: "Wyloguj",
        //DecideTradeOffers
        tradeFrom: "Oferta wymiany od",
        youGet: "Otrzymujesz",
        youGive: "Dajesz",
        accept: "Akceptuj",
        decline: "Odrzuć",
        user1Products: "Produkty użytkownika 1",
        user2Products: "Produkty użytkownika 2",
        sendTradeoffer: "Wyślij ofertę wymiany",
        //TradeOffer
        yourInventory: "Twój ekwipunek",
        theirInventory: "Ich ekwipunek",
        itemsYouLose: "Oto przedmioty, które stracisz w trakcie wymiany.",
        theirItems: "Ich przedmioty",
        itemsYouReceive: "Oto przedmioty, które otrzymasz w trakcie wymiany.",
        //Tradeoffers
        itemsYouGive: "Przedmioty, które oddasz",
        noPendingTradeoffers: "Nie masz żadnych oczekujących ofert wymiany.",
        historyTradeoffer: "Historia twoich ofert wymiany",
        trader: "Handlarz",
        yourItems: "Twoje przedmioty",
        traderItems: "Przedmioty handlarza",
        date: "Data",
        noPreviousTrades: "Nie masz wcześniejszych transakcji.",
        tradeOfferAccept: "Akceptuj",
        tradeOfferDecline: "Odrzuć",
        tradeOffersUrOffer: "Oferowałeś",
        tradeOffersNoOffer: "Użytkownik nie ma żadnych ofert wymiany.",
        incommingTradeOffer: "zaproponował ci",
        offeredItem: "za twój",
        accepted: "Zaakceptowane",
        declined: "Odrzucone",
        canceled: "Anulowane",
        by: "przez",
        for: "dla",
        sItems: "przedmioty",
        //User
        userDetails: "Szczegóły użytkownika",
        tradeOffer: "Oferta wymiany",
        checkout: "Do kasy",
        userStudios: "Studio użytkownika",
        Checkout: "Sprawdź",
        //BuyKey
        appActivation: "Aktywacja aplikacji",
        verify: "Zweryfikuj",
        keyPurchase: "Zakup klucza",
        buyLicenseKey: "Kup klucz licencyjny",
        clickToCopy: "Kliknij, aby skopiować do schowka",
      }
    },
    de: {
      translation: {
        //Sidebar
        store: "Geschäft",
        library: "Bibliothek",
        studios: "Studios",
        studio: "Studio",
        tradeOffers: "Tauschangebote",
        adminPanel: "Admin-Panel",
        getFullVersion: "Vollversion erhalten",
        cart: "Warenkorb",
        //Library
        yourLibrary: "Deine Bibliothek",
        username: "Benutzername",
        surname: "Nachname",
        preferedTheme: "Bevorzugtes Thema",
        credits: "Credits",
        noProducts: "Sie haben derzeit keine Produkte.",
        //Admin
        delete: "Löschen",
        addAdmin: "Admin hinzufügen",
        deleteAdmin: "Admin entfernen",
        users: "Benutzer",
        album: "Album",
        product: "Produkt",
        remove: "Entfernen",
        adminPanelUsersCount: "Aktive Benutzer",
        adminPanelTotalCredits: "Gesamtkredite",
        adminPanelTopContributors: "Top-Mitwirkende",
        adminPanelTopUser: "Top-Benutzer",
        adminAddedSuccessfully: "Admin wurde erfolgreich hinzugefügt.",
        adminNotAdded: "Admin konnte nicht hinzugefügt werden.",
        adminDeletedSuccessfully: "Admin wurde erfolgreich entfernt.",
        adminNotDeleted: "Admin konnte nicht entfernt werden.",
        userDeletedSuccessfully: "Benutzer wurde erfolgreich entfernt.",
        userNotDeleted: "Benutzer konnte nicht entfernt werden.",
        ownershipChangedSuccessfully: "Eigentum wurde erfolgreich geändert.",
        ownershipNotChanged: "Eigentum konnte nicht geändert werden.",
        //Cart
        totalCost: "Gesamtkosten",
        noCartItems: "Dein Warenkorb ist leer. Füge Produkte hinzu, um fortzufahren.",
        cartOf: "Warenkorb von",
        addToCart: "In den Warenkorb legen",
        purchaseMadeSuccessfully: "Der Kauf wurde erfolgreich abgeschlossen.",
        purchase: "Kauf",
        insufficientFunds: "Unzureichende Mittel",
        //PurchaseHistory
        purchaseHistory: "Kaufhistorie von",
        noPurchases: "Sie haben keine Einkäufe.",

        //Settings
        save: "Speichern",
        cancel: "Abbrechen",
        exportUserInfo: "Benutzerinformationen exportieren",
        name: "Name",
        email: "E-Mail",
        bio: "Bio",
        noBio: "Du hast keine Bio.",
        otherSettings: "Weitere Einstellungen",
        themes: "Themen",
        privateData: "Private Daten",
        profileSettings: "Profileinstellungen",
        informationAlteredSuccessfully: "Informationen wurden erfolgreich geändert.",
        informationNotAltered: "Informationen wurden nicht geändert.",
        //CreateItem
        nameOfTrack: "Titel des Songs",
        producer: "Produzent",
        songDuration: "Songdauer in Sekunden",
        createYourItem: "Erstelle deinen Artikel",
        createItem: "Artikel erstellen",
        picPreview: "Hier ist eine schnelle Vorschau deines Artikelbildes!",
        newItemName: "Wie möchtest du dein Produkt nennen?",
        newAlbumName: "Albumname",
        newAlbumCreator: "Künstler",
        newAlbumDescription: "Beschreibung",
        newAlbumPrice: "Preis",
        tags: "Tags",
        provideValidProductName: "Geben Sie einen gültigen Produktnamen an.",
        provideValidArtist: "Geben Sie einen gültigen Künstlernamen an.",
        provideValidDescription: "Geben Sie eine gültige Beschreibung an (mindestens 10 Zeichen).",
        provideValidPrice: "Geben Sie einen gültigen Preis an.",
        selectOneTag: "Wählen Sie mindestens 1 Tag aus.",
        someSongTitlesInvalid: "Einige Liedtitel sind ungültig.",
        someSongProducersInvalid: "Einige der Produzenten der Lieder sind ungültig.",

        //Item
        viewDetails: "Details anzeigen",
        albumDetails: "Albumdetails",
        otherProducts: "Andere Produkte",
        //CreateStudio
        createYourStudio: "Erstelle dein Studio",
        studioImagePreview: "Hier ist eine schnelle Vorschau deines Studio-Bildes!",
        uploadPhoto: "Foto hochladen",
        studioName: "Wie möchtest du dein Studio nennen?",
        placeholderName: "Name",
        studioDesc: "Erzähle uns mehr über dein Studio!",
        placeholderDesc: "Beschreibung",
        createStudioNotif: "*Du kannst später Änderungen vornehmen",
        createStudio: "Studio erstellen",
        nameLengthNotif: "*Der Name sollte zwischen 3 und 30 Zeichen enthalten",
        descLengthNotif: "*Die Beschreibung sollte zwischen 10 und 100 Zeichen enthalten",
        nameLengthError: "Geben Sie einen gültigen Studionamen ein (zwischen 3 und 30 Zeichen).",
        descLengthError: "Geben Sie eine gültige Studio-Beschreibung ein (zwischen 10 und 100 Zeichen).",
        nameTakenError: "Der Studio-Name ist bereits vergeben.",
        //EditStudio
        editYourStudio: "Studio bearbeiten",
        studioNameEdit: "Wie möchtest du dein Studio umbenennen?",
        //Studio
        studioDetails: "Studio-Details",
        studioOwned: "Im Besitz von",
        otherStudios: "Andere Studios",
        studioAlbums: "Studioalben",
        viewProfile: "Profil anzeigen",
        //Studios
        studioDeletionMessage: "Diese Aktion kann nicht rückgängig gemacht werden. Bist du dir zu 100% sicher?",
        confirm: "Bestätigen",
        learnMore: "Mehr erfahren",
        myStudios: "Meine Studios",
        edit: "Bearbeiten",
        //TopBar
        search: "Suchen",
        //Menu
        darkMode: "Dunkler Modus",
        termsOfUse: "Nutzungsbedingungen",
        settings: "Einstellungen",
        addFunds: "Guthaben hinzufügen",
        logout: "Abmelden",
        //DecideTradeOffers
        tradeFrom: "Tauschangebot von",
        youGet: "Du bekommst",
        youGive: "Du gibst",
        accept: "Annehmen",
        decline: "Ablehnen",
        user1Products: "Produkte von Benutzer 1",
        user2Products: "Produkte von Benutzer 2",
        sendTradeoffer: "Tauschangebot senden",
        //TradeOffer
        yourInventory: "Dein Inventar",
        theirInventory: "Ihr Inventar",
        itemsYouLose: "Dies sind die Gegenstände, die du bei dem Tausch verlierst.",
        theirItems: "Ihre Gegenstände",
        itemsYouReceive: "Dies sind die Gegenstände, die du beim Tausch erhältst.",
        //Tradeoffers
        itemsYouGive: "Gegenstände, die du gibst",
        noPendingTradeoffers: "Du hast keine ausstehenden Tauschangebote.",
        historyTradeoffer: "Historie deiner Tauschangebote",
        trader: "Händler",
        yourItems: "Deine Gegenstände",
        traderItems: "Gegenstände des Händlers",
        date: "Datum",
        noPreviousTrades: "Du hast keine vorherigen Transaktionen.",
        tradeOfferAccept: "Annehmen",
        tradeOfferDecline: "Ablehnen",
        tradeOffersUrOffer: "Du hast angeboten",
        tradeOffersNoOffer: "Der Benutzer hat keine Tauschangebote.",
        incommingTradeOffer: "hat dir angeboten",
        offeredItem: "für deinen",
        accepted: "Akzeptiert",
        declined: "Abgelehnt",
        canceled: "Storniert",
        by: "von",
        for: "für",
        sItems: "Gegenstände",
        //User
        userDetails: "Benutzerdetails",
        tradeOffer: "Tauschangebot",
        checkout: "Zur Kasse",
        userStudios: "Benutzerstudios",
        Checkout: "Check out",
        //BuyKey
        appActivation: "App-Aktivierung",
        verify: "Verifizieren",
        keyPurchase: "Schlüssel kaufen",
        buyLicenseKey: "Lizenzschlüssel kaufen",
        clickToCopy: "Klicken, um in die Zwischenablage zu kopieren",
      },
    }
  }
})

